export type Job = {
  id: number;
  title: string;
  project: string;
  location: string;
  salary: string;
  salaryFull: string;
  experience: string;
  vacancies: number;
  lastDate: string;
  shiftTiming: string;
  department: string;
  qualification: string;
  description: string;
  responsibilities: string[];
  qualifications: string[];
  documents: string[];
};

export const allJobs: Job[] = [
  {
    id: 1,
    title: "Senior Civil Engineer - Highway",
    project: "[Associated Project: NHAI HIGHWAY PHASE-4]",
    location: "NHAI Highway Phase-4",
    salary: "₹4.00 - 2,000",
    salaryFull: "INR 12,00,000 - 18,00,000 P.A.",
    experience: "5-10 years",
    vacancies: 6,
    lastDate: "29 Apr 2023",
    shiftTiming: "Full-Time, 9 AM - 6 PM",
    department: "Government",
    qualification: "M.Tech Preferred",
    description:
      "Senior Civil Engineer - Highway [Associated Project: NHAI HIGHWAY Phase-4] government projects. Location: and subwis roid sector projects, brainway and siection omerbas in depats of sans and mentations and accesstoe progators need for goiernment projects.",
    responsibilities: [
      "Proceeding and remnotery plagoment for areas of highway",
      "Detective approvaitation from high collaboration",
      "Working attemproavement erating and sectings",
      "Developing and confattoneed engineering smi government contractors",
    ],
    qualifications: ["B.Tech Civil, M.Tech preferred", "B.Tech Civil, preferred"],
    documents: [
      "Degree, Documissier Certification",
      "Experience Certificates, Experience Certificates",
      "IDs, Contracors, IDs, IDs, Rurdiee Card",
    ],
  },
  {
    id: 2,
    title: "Senior Civil Engineer - Highway",
    project: "[Associated Project: NHAI HIGHWAY PHASE-4]",
    location: "Metro Line-3, Delhi",
    salary: "₹8.00 - 2,000",
    salaryFull: "INR 12,00,000 - 18,00,000 P.A.",
    experience: "2+",
    vacancies: 7,
    lastDate: "28 Apr 2023",
    shiftTiming: "Full-Time, 9 AM - 6 PM",
    department: "Environmental",
    qualification: "M.Tech Preferred",
    description:
      "Senior Civil Engineer for Metro Line-3 expansion project in Delhi. Responsible for overseeing highway and metro corridor civil works, ensuring compliance with government standards and project specifications.",
    responsibilities: [
      "Supervising civil construction work at Metro Line-3 site",
      "Coordinating with project management teams",
      "Preparing technical reports and documentation",
      "Ensuring quality control and safety standards",
    ],
    qualifications: ["B.Tech Civil Engineering", "M.Tech preferred with 2+ years experience"],
    documents: ["Degree Certificate", "Experience Certificates", "Government ID Proof", "Resume/CV"],
  },
  {
    id: 3,
    title: "Senior Civil Engineer - Highway",
    project: "[Associated Project: NHAI HIGHWAY PHASE-4]",
    location: "NHAI Highway Phase-4",
    salary: "₹8.00 - 2,000",
    salaryFull: "INR 14,00,000 - 20,00,000 P.A.",
    experience: "4+",
    vacancies: 6,
    lastDate: "29 Apr 2023",
    shiftTiming: "Full-Time, 8 AM - 5 PM",
    department: "Government",
    qualification: "B.Tech Civil",
    description:
      "Experienced civil engineer required for NHAI Highway Phase-4 project. The candidate will be responsible for managing highway construction, surveying, and quality assurance activities.",
    responsibilities: [
      "Managing highway construction activities",
      "Conducting site surveys and inspections",
      "Coordinating with sub-contractors and vendors",
      "Maintaining project documentation and progress reports",
    ],
    qualifications: ["B.Tech Civil with 4+ years experience", "Knowledge of highway construction standards"],
    documents: ["Educational Certificates", "Work Experience Letters", "Photo ID", "PAN Card"],
  },
  {
    id: 4,
    title: "Accountant - NHAI",
    project: "(NHAI HQ, Noida)",
    location: "NHAI HQ, Noida",
    salary: "₹1.00 - 2,000",
    salaryFull: "INR 6,00,000 - 10,00,000 P.A.",
    experience: "2+",
    vacancies: 17,
    lastDate: "21 Apr 2023",
    shiftTiming: "Full-Time, 9 AM - 6 PM",
    department: "Communication",
    qualification: "B.Com / CA",
    description:
      "Accountant required at NHAI HQ, Noida for managing financial records, preparing budgets, and ensuring compliance with government accounting standards for public sector tenders.",
    responsibilities: [
      "Maintaining financial records and ledgers",
      "Preparing monthly/quarterly financial reports",
      "Handling GST filings and tax compliance",
      "Coordinating with auditors for annual audits",
    ],
    qualifications: ["B.Com or CA qualification", "2+ years experience in government accounting", "Tally/ERP proficiency"],
    documents: ["Degree Certificate", "CA Certificate (if applicable)", "Experience Letters", "Aadhar & PAN Card"],
  },
  {
    id: 5,
    title: "Senior Civil Engineer - Highway",
    project: "[NHAI HQ, Phase-4]",
    location: "Metro HQ, Phase-4",
    salary: "₹1.00 - 2,000",
    salaryFull: "INR 10,00,000 - 15,00,000 P.A.",
    experience: "3+",
    vacancies: 17,
    lastDate: "29 Apr 2023",
    shiftTiming: "Full-Time, 9 AM - 5 PM",
    department: "Government",
    qualification: "B.Tech Civil",
    description:
      "Civil Engineer for Metro HQ Phase-4 project handling structural design, site supervision, and quality management for government infrastructure.",
    responsibilities: [
      "Structural design and analysis",
      "Site supervision and quality checks",
      "Liaison with government departments",
      "Preparation of BOQ and cost estimates",
    ],
    qualifications: ["B.Tech Civil Engineering", "3+ years in infrastructure projects"],
    documents: ["Degree Certificate", "Experience Letters", "Photo ID"],
  },
  {
    id: 6,
    title: "Senior Civil Engineer - Highway",
    project: "[NHAI Highway Phase-4]",
    location: "Metro HQ, Noida",
    salary: "₹8.00 - 2,000",
    salaryFull: "INR 16,00,000 - 22,00,000 P.A.",
    experience: "5+",
    vacancies: 17,
    lastDate: "29 Apr 2023",
    shiftTiming: "Full-Time, 9 AM - 6 PM",
    department: "Environmental",
    qualification: "M.Tech Preferred",
    description:
      "Senior civil engineer with expertise in environmental compliance for highway projects under NHAI Phase-4 initiative.",
    responsibilities: [
      "Environmental impact assessment for highway routes",
      "Coordinating with NHAI environmental team",
      "Ensuring eco-friendly construction practices",
      "Reporting to project directors",
    ],
    qualifications: ["B.Tech/M.Tech Civil", "5+ years highway experience", "Environmental clearance knowledge"],
    documents: ["Degree", "Experience Certificates", "Govt ID"],
  },
  {
    id: 7,
    title: "Senior Civil Engineer - Highway",
    project: "[NHAI Highway Phase-4]",
    location: "Metro HQ, Noida",
    salary: "₹1.00 - 2,000",
    salaryFull: "INR 9,00,000 - 13,00,000 P.A.",
    experience: "2+",
    vacancies: 17,
    lastDate: "29 Apr 2023",
    shiftTiming: "Full-Time, 8 AM - 6 PM",
    department: "Government",
    qualification: "B.Tech Civil",
    description:
      "Junior to mid-level civil engineer for NHAI highway expansion project. Candidate should have hands-on experience in road construction and project coordination.",
    responsibilities: [
      "Assisting senior engineers in site management",
      "Surveying and testing road materials",
      "Maintaining site safety standards",
      "Filing daily progress reports",
    ],
    qualifications: ["B.Tech Civil", "2+ years road construction experience"],
    documents: ["Degree", "Experience Letters", "ID Proof", "Resume"],
  },
  {
    id: 8,
    title: "Senior Civil Engineer - Highway",
    project: "(Highway, Noida)",
    location: "NHAI HQ, Noida",
    salary: "₹1.00 - 2,000",
    salaryFull: "INR 8,00,000 - 12,00,000 P.A.",
    experience: "1+",
    vacancies: 17,
    lastDate: "29 Apr 2023",
    shiftTiming: "Full-Time, 9 AM - 6 PM",
    department: "Communication",
    qualification: "B.Tech Civil",
    description:
      "Entry-level civil engineer for Noida highway project. Freshers with strong academic background in civil engineering are encouraged to apply.",
    responsibilities: [
      "Supporting design and drafting activities",
      "Assisting in on-site inspections",
      "Data collection and analysis",
      "Coordination with project team",
    ],
    qualifications: ["B.Tech Civil Engineering", "1+ year experience preferred"],
    documents: ["Degree Certificate", "ID Proof", "Resume/CV"],
  },
  {
    id: 9,
    title: "Project Manager - Metro",
    project: "[Metro Line-3, Delhi]",
    location: "Metro Line-3, Delhi",
    salary: "₹9.00 - 3,000",
    salaryFull: "INR 20,00,000 - 30,00,000 P.A.",
    experience: "5+",
    vacancies: 5,
    lastDate: "30 Apr 2023",
    shiftTiming: "Full-Time, 9 AM - 7 PM",
    department: "Government",
    qualification: "B.Tech + MBA",
    description:
      "Project Manager for Delhi Metro Line-3 expansion. Responsible for end-to-end project delivery, stakeholder management, and government compliance.",
    responsibilities: [
      "End-to-end project delivery management",
      "Stakeholder and government liaison",
      "Budget control and resource planning",
      "Risk assessment and mitigation",
    ],
    qualifications: ["B.Tech with MBA or equivalent", "5+ years in infrastructure PM", "PMP certification preferred"],
    documents: ["Degree & MBA Certificate", "PMP Certificate", "Experience Letters", "Govt ID"],
  },
  {
    id: 10,
    title: "Site Engineer - PWD",
    project: "[PWD Project #402, Mumbai]",
    location: "PWD Project, Mumbai",
    salary: "₹4.00 - 2,000",
    salaryFull: "INR 6,00,000 - 9,00,000 P.A.",
    experience: "2+",
    vacancies: 6,
    lastDate: "29 Apr 2023",
    shiftTiming: "Full-Time, 8 AM - 5 PM",
    department: "Environmental",
    qualification: "Diploma / B.Tech Civil",
    description:
      "Site Engineer for PWD Project #402 in Mumbai. The candidate will oversee day-to-day construction activities and ensure timely completion of milestones.",
    responsibilities: [
      "Day-to-day site supervision",
      "Coordination with contractors",
      "Quality and safety compliance",
      "Progress reporting to senior PM",
    ],
    qualifications: ["Diploma or B.Tech Civil", "2+ years site experience"],
    documents: ["Degree/Diploma", "Experience Letters", "ID Proof"],
  },
  {
    id: 11,
    title: "Safety Officer - NHAI",
    project: "[NHAI Highway Phase-4]",
    location: "NHAI Highway Phase-4",
    salary: "₹3.00 - 1,500",
    salaryFull: "INR 5,00,000 - 8,00,000 P.A.",
    experience: "3+",
    vacancies: 4,
    lastDate: "27 Apr 2023",
    shiftTiming: "Full-Time, 7 AM - 4 PM",
    department: "Government",
    qualification: "Diploma in Safety",
    description:
      "Safety Officer for NHAI Highway Phase-4 project. Responsible for implementing and monitoring health, safety, and environment (HSE) protocols on construction sites.",
    responsibilities: [
      "Conducting daily safety inspections",
      "Training workers on safety protocols",
      "Incident reporting and investigation",
      "Ensuring PPE compliance on site",
    ],
    qualifications: ["Diploma in Industrial Safety", "3+ years in construction HSE", "NEBOSH/IOSH certification preferred"],
    documents: ["Safety Diploma/Certificate", "NEBOSH/IOSH Certificate", "Experience Letters", "ID Proof"],
  },
  {
    id: 12,
    title: "Survey Engineer",
    project: "[NHAI HQ, Phase-4]",
    location: "NHAI HQ, Noida",
    salary: "₹5.00 - 2,500",
    salaryFull: "INR 7,00,000 - 11,00,000 P.A.",
    experience: "2+",
    vacancies: 8,
    lastDate: "26 Apr 2023",
    shiftTiming: "Full-Time, 8 AM - 6 PM",
    department: "Communication",
    qualification: "B.Tech Civil / Survey",
    description:
      "Survey Engineer for NHAI HQ Phase-4 project. Responsible for topographic surveys, alignment studies, and preparing survey reports for highway construction activities.",
    responsibilities: [
      "Conducting topographic and hydrographic surveys",
      "Operating total station and GPS equipment",
      "Preparing survey drawings and reports",
      "Coordinating with design and construction teams",
    ],
    qualifications: ["B.Tech Civil or Survey Engineering", "2+ years survey experience", "AutoCAD proficiency"],
    documents: ["Degree Certificate", "Experience Letters", "AutoCAD Certification (optional)", "ID Proof"],
  },
];
